server:
  port: 8001
spring:
  application:
    name: invoicing-system-provider
  #数据源连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.86.82:3306/invoicing_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: senge
    #druid连接池
    druid:
      initial-size: 5   #初始化连接大小
      min-idle: 5 #最小连接池数量
      max-active: 20  #最大连接池数量
      max-wait: 60000 #获取连接时最大的等待时间
      time-between-eviaction-runs-millis: 60000  #配置间隔多久才进行一次检测
      min-evictable-idle-time-millis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
      test-while-idle: true #申请连接的时候检测，建议配置为true，不影响性能，并且保证安
      test-on-borrow: false #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 39.96.86.82
    pool: 6379
    database: 2
mybatis-plus:
  global-config:
    db-config:
      table-underline: true
      id-type: input
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/invoicingsystem/*Mapper.xml,classpath:mapper/invoicingsystem/vo/*Mapper.xml
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
